services:
  app:
    image: ghcr.io/lakwli/memorieswalk:app
    container_name: memorieswalk
    environment:
      JWT_SECRET: change_this_to_a_secure_random_string
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - memorieswalk_data:/app/server/file_storage
    restart: on-failure

  db:
    image: ghcr.io/lakwli/memorieswalk:db
    container_name: memorieswalkdb
    volumes:
      - memorieswalk_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  memorieswalk_data:
  memorieswalk_db_data:
