name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Add QEMU for multi-architecture support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # Set up Docker Buildx for multi-architecture builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push APP Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Build native images for both architectures
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENABLE_CONSOLE_OUTPUT=false
          tags: |
            ghcr.io/${{ github.repository }}:app
        
      - name: Build and push DB Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./db.Dockerfile
          push: true
          # Build native images for both architectures
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENABLE_CONSOLE_OUTPUT=false
          tags: |
            ghcr.io/${{ github.repository }}:db
      